# Generated by Django 4.1.4 on 2022-12-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "functional_state",
                    models.TextField(
                        choices=[
                            ("A", "Functional Status A"),
                            ("B", "Functional Status B"),
                            ("C", "Functional Status C"),
                            ("D", "Functional Status D"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "connection_state",
                    models.TextField(
                        choices=[
                            ("monitored", "Monitored"),
                            ("powered", "Powered"),
                            ("connected", "Connected"),
                            ("not connected", "Not Connected"),
                        ],
                        max_length=100,
                    ),
                ),
                ("parameters", models.TextField()),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="specifications.specification",
                    ),
                ),
            ],
        ),
    ]
