# Generated by Django 4.1.3 on 2022-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("specification", models.CharField(max_length=200)),
                ("duration", models.PositiveIntegerField()),
            ],
        ),
    ]
