# Generated by Django 4.1.4 on 2022-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
