# Generated by Django 4.1.4 on 2022-12-08 09:31

import auth_demo.auth_app.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_myuser_groups_myuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("object", auth_demo.auth_app.managers.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
